### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by Betapoisoner** [mstuttgart/dotfiles#10]
I have the same mint version as you and half the apps fails to install, also when nohing fails intalling i3 chrashes when opening

**Comment by mstuttgart** [comment]
> when nohing fails intalling i3 chrashes when opening

You need to install i3-gaps. the default i3 version in package manager crashes with my i3 config. 

> I have the same mint version as you and half the apps fails to install

Please, can you list then?

**Comment by Betapoisoner** [comment]
The apps that fail are mvp arand amd i3 gaps shows an error

**Comment by mstuttgart** [comment]
@Betapoisoner fixed. thanks
