### ISSUE TITLE
Fedora 39 Error

### ISSUE THREAD

**Issue by kinjar1988** [mstuttgart/dotfiles#9]
I try to install your dotfiles in Fedora 39. Everything is ok but in last step (yadm bootstrap) an error is coming.

Error : sudo : apt command not found.

Is there any solution for this ?

**Comment by mstuttgart** [comment]
Hi @kinjar1988 , this command APT package manager, from Debian based distros (Ubuntu, Linux Mint, Elementary OS e etc). Fedora insted uses RPM package manager. Unfortunately, my dotfiles not is compatible with RPM. 

You need to open the bootstrap file (~/.config/yadm/bootstrap) and change each one of apt package to its equivalent in RPM package manager ecosystem. Please let me know if I can help with anything
